apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
      - name: kanban-app
        image: your-kanban-app-image:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "50m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_RUN_PORT
          value: "8000"

